///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// class LoginModel {
// /*
// {
//   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NzNhYWI0NjRmMWY1YTRmOGVjMDYxZSIsInVzZXJuYW1lIjoicHVuZXNhbCIsInJvbGUiOjUsImlhdCI6MTczNTkwMTUxOCwiZXhwIjoxNzM1OTg3OTE4fQ.uGqxS0GCBp4Ef7POXPCVmvQlcNL2M2MSu3Nq7kxERyA",
//   "role": 5
// }
// */
//
//   String? token;
//   int? role;
//
//   LoginModel({
//     this.token,
//     this.role,
//   });
//   LoginModel.fromJson(Map<String, dynamic> json) {
//     token = json['token']?.toString();
//     role = json['role']?.toInt();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['token'] = token;
//     data['role'] = role;
//     return data;
//   }
// }

// /
// / Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
//
// / admin response
// class LoginModel {
//   String? message;
//   String? token;
//   int? role;
//   String? username;
//
//   LoginModel({this.message, this.token, this.role, this.username});
//
//   LoginModel.fromJson(Map<String, dynamic> json) {
//     message = json['message'];
//     token = json['token'];
//     role = json['role'];
//     username = json['username'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['message'] = this.message;
//     data['token'] = this.token;
//     data['role'] = this.role;
//     data['username'] = this.username;
//     return data;
//   }
// }



class LoginModel {
  String? message;
  String?
  token;
  int? role;
  String? username;

  // Constructor
  LoginModel({this.message, this.token, this.role, this.username});

  // Factory constructor to create a LoginModel from JSON
  LoginModel.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    token = json['token'];
    role = json['role'];
    username = json['username'];
  }

  // Method to convert LoginModel to JSON
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['message'] = this.message;
    data['token'] = this.token;
    data['role'] = this.role;
    data['username'] = this.username;
    return data;
  }

  // Method to identify if the user is an admin or salesman
  bool isAdmin() {
    return role == 4; // Admin role
  }

  bool isSalesman() {
    return role == 5; // Salesman role
  }
}


// class LoginModel {
//   String? message;
//   String? token;
//   int? role;
//   String? username;
//
//   LoginModel({this.message, this.token, this.role, this.username});
//
//   LoginModel.fromJson(Map<String, dynamic> json) {
//     message = json['message'];
//     token = json['token'];
//     role = json['role'];
//     username = json['username'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['message'] = this.message;
//     data['token'] = this.token;
//     data['role'] = this.role;
//     data['username'] = this.username;
//     return data;
//   }
// }



